### ISSUE TITLE
Create /token/ and /token/refresh/ endpoints for Django authentication with JWT

### ISSUE THREAD

**Issue by ziyapx** [djangoflow/django-df-auth#1]
Create functionality to support REST API login through `/token/*` endpoints returning JWTs back to the clients.

**Endpoints:**
* token/
* token/refresh

**Views and Serializers:** Create classes for each endpoint

**Routing:** Should use DRF router

**Settings:** Create required settings e.g. for pluggable model - default to Django default user model

**Unit tests:** Create unit tests per endpoint and cover edge scenarios

**Comment by ayushin** [comment]
All done, but testing, creating a new issue for that.
