### ISSUE TITLE
Need to add optional first_name and last_name for auth_social_create endpoint

### ISSUE THREAD

**Issue by adar2378** [djangoflow/django-df-auth#13]
https://api.hlcafe.dev/api/v1/#tag/auth/operation/auth_social_create

Need to add optional first_name and last_name here in order to pass apple login firstName and lastName as apple login only gives it to frontend.

**Comment by ayushin** [comment]
need:
1. Mixin for first_name last_name
2. Add this mixin to SocialTokenObtainSerializer
3. Find a way to integrate that into the social create user pipeline

**Comment by ayushin** [comment]
fixed in 0.16
