### ISSUE TITLE
Integrate python-social-auth REST endpoints

### ISSUE THREAD

**Issue by ayushin** [djangoflow/django-df-auth#2]
The following endpoints should be implemented:

`/social/signin/(facebook|google|apple)` - obtain token by exchanging `access` / `code` / `id` / `id token` as needed from the respective social platform, i.e. rest  endpoints, not login redirect screen

`/social/connect/(facebook|google|apple)`  - connect respective social account to the user currently authorised

The rest of the `/social` endpoints from social_auth.urls should be merged into the above.

Requirements:
 - the code should be DRY
 - social auth configuration via environment variables

You most likely would have to create one or more `ViewSet`s  and `Serializer`s and call respective `social_auth` methods for the actual work.

**Comment by ayushin** [comment]
Signup completed with https://github.com/djangoflow/django-df-auth/pull/6

Still open:
- connect / disconnect (few lines of code)
- documentation for integration

**Comment by ayushin** [comment]
Connect still missing.

**Comment by eugen1j** [comment]
Added https://github.com/djangoflow/django-df-auth/pull/10 for Connect
