### ISSUE TITLE
Confirming OTPDevice throws 400 error

### ISSUE THREAD

**Issue by adar2378** [djangoflow/django-df-auth#37]
I have an OTPDevice
```json
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 2,
      "name": "saiful@apexive.com",
      "type": "email",
      "confirmed": false,
      "key": null
    }
  ]
}
```

- I am requesting OTP via POST `/api/v1/auth/otp/` and getting OTP code
- I am confirming my device via POST `api/v1/auth/otp-device/2/confirm/`
Payload:
```json
{"code":"068096"}
```

Getting error: status code = 400,
```json
{
  "errors": [
    {
      "message": "Invalid device type. Must be one of email, totp, sms",
      "code": "invalid"
    }
  ]
}
```

**Comment by eugapx** [comment]
@adar2378 You need to pass type in URL `api/v1/auth/otp-device/2/confirm/?type=email`.

**Comment by eugapx** [comment]
I fixed the API schema, added `type` param, so should work now
