### ISSUE TITLE
Create unit tests for existing ViewSets

### ISSUE THREAD

**Issue by ayushin** [djangoflow/django-df-auth#8]
[ ] TokenViewSet
[ ] SocialTokenViewSet

**Comment by rishistrive** [comment]
Hi @ziyapx, I've some questions regarding the task:

1. How can I get `access_token` to pass as an argument in `/social` endpoint.
2. How can I get `refresh` token to pass as an argument in `/token/refresh` and `/token/blacklist` endpoints.
3. How can I get `token` to pass as an argument in `/token/verify` endpoint.
4. I'm getting `TypeError` while accessing `/token/signup` endpoint with GET and POST method.

**Comment by rishistrive** [comment]
Hi @ziyapx, I've some questions regarding the task:

1. How can I get `access_token` to pass as an argument in `/social` endpoint.
2. How can I get `refresh` token to pass as an argument in `/token/refresh` and `/token/blacklist` endpoints.
3. How can I get `token` to pass as an argument in `/token/verify` endpoint.
4. I'm getting `No matching authorization backend` message while hitting `/token/signup/` endpoint, with POST request.

**Comment by ziyapx** [comment]
> Hi @ziyapx, I've some questions regarding the task:
> 
> 1. How can I get `access_token` to pass as an argument in `/social` endpoint.
> 2. How can I get `refresh` token to pass as an argument in `/token/refresh` and `/token/blacklist` endpoints.
> 3. How can I get `token` to pass as an argument in `/token/verify` endpoint.
> 4. I'm getting `No matching authorization backend` message while hitting `/token/signup/` endpoint, with POST request.

@rishistrive  I think you can mock certain parts to by-pass code that isn't in our library. Also you might need to change test settings. What do you think @ayushin ?
